resources:
  jobs:
    workbridge_workforce_analytics_job:
      name: workbridge_workforce_analytics_job
      schedule:
        quartz_cron_expression: 22 0 8 1 * ?
        timezone_id: America/Buenos_Aires
        pause_status: UNPAUSED
      tasks:
        - task_key: 01_ingest_bronze
          notebook_task:
            notebook_path: /Workspace/workbridge_workforce_analytics/01_ingest_bronze
            source: WORKSPACE
        - task_key: 02_validate_bronze
          depends_on:
            - task_key: 01_ingest_bronze
          notebook_task:
            notebook_path: /Workspace/workbridge_workforce_analytics/02_validate_bronze
            source: WORKSPACE
        - task_key: 03_transform_silver
          depends_on:
            - task_key: 02_validate_bronze
          notebook_task:
            notebook_path: /Workspace/workbridge_workforce_analytics/03_transform_silver
            source: WORKSPACE
        - task_key: 04_validate_silver
          depends_on:
            - task_key: 03_transform_silver
          notebook_task:
            notebook_path: /Workspace/workbridge_workforce_analytics/04_validate_silver
            source: WORKSPACE
        - task_key: 05_build_gold
          depends_on:
            - task_key: 04_validate_silver
          notebook_task:
            notebook_path: /Workspace/workbridge_workforce_analytics/05_build_gold
            source: WORKSPACE
        - task_key: 06_validate_gold
          depends_on:
            - task_key: 05_build_gold
          notebook_task:
            notebook_path: /Workspace/workbridge_workforce_analytics/06_validate_gold
            source: WORKSPACE
      queue:
        enabled: true
      performance_target: PERFORMANCE_OPTIMIZED
